/*
    Copyright 2015-2024 MCGalaxy
    Dual-licensed under the Educational Community License, Version 2.0 and
    the GNU General Public License, Version 3 (the "Licenses"); you may
    not use this file except in compliance with the Licenses. You may
    obtain a copy of the Licenses at
    https://opensource.org/license/ecl-2-0/
    https://www.gnu.org/licenses/gpl-3.0.html
    Unless required by applicable law or agreed to in writing,
    software distributed under the Licenses are distributed on an "AS IS"
    BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
    or implied. See the Licenses for the specific language governing
    permissions and limitations under the Licenses.
 */
using System;
using System.Collections.Generic;
namespace MCGalaxy.Generator.Foliage
{
    public delegate void TreeOutput(ushort x, ushort y, ushort z, ushort block);
    public delegate Tree TreeConstructor();
    public abstract class Tree
    {
        public ushort LeafBlock = Block.Leaves, TrunkBlock = Block.Log;
        protected internal int height, size;
        protected Random rnd;
        /// <summary> Minimum allowed size (usually means height) for this tree. </summary>
        public virtual int MinSize => 3;
        /// <summary> Estimated the maximum number of blocks affected by this tree. </summary>
        public abstract long EstimateBlocksAffected();
        /// <summary> Calculates a random default size (usually means height) for this tree. </summary>
        public abstract int DefaultSize(Random rnd);
        /// <summary> Initalises data (e.g. height and size) for this tree using the input value. </summary>
        public abstract void SetData(Random rnd, int value);
        /// <summary> Outputs the blocks generated by this tree at the given coordinates. </summary>
        public abstract void Generate(ushort x, ushort y, ushort z, TreeOutput output);

        public static Dictionary<string, TreeConstructor> TreeTypes = new() 
        {
            { "Fern", () => new NormalTree() },
            { "Swamp", () => new SwampTree() },
            { "Oak", () => new OakTree() }
        };
    }
}