/*
    Copyright 2015-2024 MCGalaxy
    Dual-licensed under the Educational Community License, Version 2.0 and
    the GNU General Public License, Version 3 (the "Licenses"); you may
    not use this file except in compliance with the Licenses. You may
    obtain a copy of the Licenses at
    https://opensource.org/license/ecl-2-0/
    https://www.gnu.org/licenses/gpl-3.0.html
    Unless required by applicable law or agreed to in writing,
    software distributed under the Licenses are distributed on an "AS IS"
    BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
    or implied. See the Licenses for the specific language governing
    permissions and limitations under the Licenses.
 */
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
namespace MCGalaxy.Authentication
{
    public class AuthService
    {
        public static List<AuthService> Services = new();
        public string URL, Salt, NameSuffix = "", SkinPrefix = "";
        public void AcceptPlayer(Player p)
        {
            p.VerifiedVia = URL;
            p.verifiedName = true;
            p.SkinName = SkinPrefix + p.SkinName;
            string suffix = NameSuffix;
            p.name += suffix;
            p.truename += suffix;
            p.DisplayName += suffix;
        }
        public static bool AcceptableSaltChar(char c) => (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                || (c >= '0' && c <= '9');
        public static string GenerateSalt()
        {
            RandomNumberGenerator rng = RandomNumberGenerator.Create();
            char[] str = new char[32];
            byte[] one = new byte[1];
            for (int i = 0; i < str.Length;)
            {
                rng.GetBytes(one);
                if (!AcceptableSaltChar((char)one[0]))
                    continue;
                str[i] = (char)one[0]; 
                i++;
            }
            return new(str);
        }
        public static AuthService GetOrCreate(string url, bool canSave = true)
        {
            foreach (AuthService s in Services)
                if (s.URL.CaselessEq(url))
                    return s;
            AuthService service = new()
            {
                URL = url,
                Salt = GenerateSalt()
            };
            Services.Add(service);
            if (canSave)
                try
                {
                    SaveServices();
                }
                catch (Exception ex)
                {
                    Logger.LogError("Error saving authservices.properties", ex);
                }
            return service;
        }
        /// <summary> Updates list of authentication services from authservices.properties </summary>
        public static void UpdateList()
        {
            AuthService cur = null;
            PropertiesFile.Read(Paths.AuthServicesFile, ref cur, ParseProperty, '=', true);
        }
        public static void ParseProperty(string key, string value, ref AuthService cur)
        {
            if (key.CaselessEq("URL"))
                cur = GetOrCreate(value, false);
            else if (key.CaselessEq("name-suffix"))
            {
                if (cur == null)
                    return;
                cur.NameSuffix = value;
            }
            else if (key.CaselessEq("skin-prefix"))
            {
                if (cur == null)
                    return;
                cur.SkinPrefix = value;
            }
        }
        public static void SaveServices()
        {
            using StreamWriter w = FileIO.CreateGuarded(Paths.AuthServicesFile);
            w.WriteLine("# Authentication services configuration");
            w.WriteLine("#   There is no reason to modify these configuration settings, unless the server has been configured");
            w.WriteLine("#    to send heartbeats to multiple authentication services (e.g. both ClassiCube.net and BetaCraft.uk)");
            w.WriteLine("#   DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING");
            w.WriteLine();
            w.WriteLine("#URL = string");
            w.WriteLine("#   URL of the authentication service the following settings apply to");
            w.WriteLine("#   (this should be the same as one of the heartbeat URLs specified in server.properties)");
            w.WriteLine("#name-suffix = string");
            w.WriteLine("#   Characters that are appended to usernames of players that login through the authentication service");
            w.WriteLine("#   (used to prevent username collisions between authentication services that would otherwise occur)");
            w.WriteLine("#skin-prefix = string");
            w.WriteLine("#   Characters that are prefixed to skin name of players that login through the authentication service");
            w.WriteLine("#   (used to ensure players from other authentication services see the correct skin)");
            w.WriteLine();
            foreach (AuthService service in Services)
            {
                w.WriteLine("URL = " + service.URL);
                w.WriteLine("name-suffix = " + service.NameSuffix);
                w.WriteLine("skin-prefix = " + service.SkinPrefix);
                w.WriteLine();
            }
        }
    }
}