name: Build
on:
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-Build
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile MCGalaxy
        shell: bash
        id: compile
        run: |
          msbuild MCGalaxy.sln /p:Configuration=Release
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled MCGalaxy.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          SOURCE_FILE: 'bin/Release'
          DEST_NAME: 'MCGalaxy'
      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce MCGalaxy! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'