name: Check LangVersion
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-Check
  cancel-in-progress: true

jobs:
#============================================
# ============== .NET 4.0 CHECK =============
# ===========================================
  check-mono4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check MCGalaxy LangVersion using mono
        shell: bash
        id: compile
        run: |
 	  /langversion:?
          msbuild MCGalaxy.sln /p:Configuration=Release
          cp -R bin/Release bin/Release_normal
          rm bin/Release/MCGalaxy_.dll bin/Release/MCGalaxy_.pdb
          msbuild MCGalaxy/MCGalaxy_.csproj /p:Configuration=Release /t:Rebuild /p:DefineConstants="TEN_BIT_BLOCKS"

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to check MCGalaxy .NET build LangVersion!'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          DESTINATION_URL: '${{ secrets.NOTIFY_URL }}'
          WORKFLOW_NAME: 'net40'
          